version: '3.7'
services:
  dev:
    image: geiser/r-dev:latest
    container_name: r-statistic-tutorial-gamiflow_dev
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/home/rstudio 
    ports:
      - "8787:8787"
  shiny:
    build:
      context: ./docker/shiny
      target: v0.01
    image: geiser/r-statistic-tutorial-gamiflow_shiny:latest
    container_name: r-statistic-tutorial-gamiflow_shiny
    ports:
      - "3838:3838"
    volumes:
      - '.:/srv/shiny-server/r-statistic-tutorial-gamiflow'
      - './shiny_logs:/var/log/shiny-server'

