version: '3.7'
services:
  dev:
    image: geiser/r-studio:latest
    container_name: r-statistic-tutorial-gamiflow
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/home/gcc 
    ports:
      - "8787:8787"
  shiny:
    build:
      context: ./docker/shiny
      target: prod
    image: geiser/r-statistic-tutorial-gamiflow_shiny
    container_name: r-statistic-tutorial-gamiflow_shiny
    ports:
      - "3636:3838"
    volumes:
      - '.:/srv/shiny-server/r-statistic-tutorial-gamiflow'
      - './shiny_logs:/var/log/shiny-server'
