version: '3.7'
services:
  shiny:
    build:
      context: ./docker/shiny
      target: prod
    image: geiser/r-statistic-tutorial-gamiflow_shiny
    container_name: r-statistic-tutorial-gamiflow_shiny
    ports:
      - "3838:3838"
    volumes:
      - '.:/srv/shiny-server/r-statistic-tutorial-gamiflow'
      - './shiny_logs:/var/log/shiny-server'

